name: Dev workflow

on:
  pull_request:
    branches: [main, deploy-test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@feature/create-test-workflow
    with:
      operating-systems: "['ubuntu-latest']"
      python-versions: "['3.10']"
    secrets: inherit
